# Generated by Django 4.2.5 on 2023-09-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_funcionario_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='sexo',
        ),
    ]
