# Generated by Django 4.2.5 on 2023-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_funcionario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sku',
            field=models.IntegerField(default=96545, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
