# Generated by Django 4.2.5 on 2023-09-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_produto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_produtos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=5, unique=True),
        ),
    ]
